### ISSUE TITLE
BCC and CC not working?

### ISSUE THREAD

**Issue by ewilliam** [elbuo8/sendgrid-parse#1]
No B/CC email is sent when I include B/CC data. No errors, nothing.

email intended for 'to:' recipients are sent correctly, so I'm not sure what's going on.

**Comment by elbuo8** [comment]
@ewilliam post a simple snippet. I'm assuming you are also specifying a default _to_ address which will automatically get added into the SMTPAPI _TO_ field. I can show you a way to work around that.

**Comment by mpc20001** [comment]
having the same problem - email Addresses is an array of email address that i want to bcc to

var SendGrid = require("sendgrid"); 
                        SendGrid.initialize("***_", "**_*");
                        SendGrid.sendEmail({
                          to: "testemail@testemail.com",
                          from: returnEmail,
                          fromname: "support",
                          subject: emailSubject,
                          html: emailMessage,
                          bcc:emailAddresses,
                        }, {
                          success: function(httpResponse) {
                            console.log(httpResponse);
                            response.success(httpResponse);
                          },
                          error: function(httpResponse) {
                            console.error(httpResponse);
                            response.error("Uh oh, something went wrong: "+error);
                          }
                        });

**Comment by lbm** [comment]
+1. Any more news on this?

**Comment by mpc20001** [comment]
the fault was on parses end. we ended up writing out own integration script. let me know if you want it.

**Comment by odrobnik** [comment]
@mpc20001 Do you have a way to send to CC from CloudCode? I am getting an invalid email address error if I manually add the BCC Address

**Comment by cyrixmorten** [comment]
Same issue, any updates?

**Comment by mpc20001** [comment]
Give me your emails.

**Comment by cyrixmorten** [comment]
Mine is cyrixmorten@gmail.com

**Comment by odrobnik** [comment]
mine is oliver@cocoanetics.com - though this is not the one I used for sendgrid.... why do you need it?
