### ISSUE TITLE
Does this work at all?

### ISSUE THREAD

**Issue by Sinetheta** [elbuo8/sendgrid-parse#5]
What type of thing are `SENDGRID-USERNAME` and `SENDGRID-PASSOWORD`, because I have tried every combination of authentication currently available in Sendgrid, and everything returns `"text":"{\"errors\":[\"Bad username / password\"]`

**Comment by dchekanov** [comment]
Those are username and password you're using to access your SendGrid account at https://sendgrid.com/login.

**Comment by Sinetheta** [comment]
Thanks for the reply, although it's a little surprising that you send your actual login credentials and not an api key.
